/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lucasrochagit.views;


import com.lucasrochagit.aws.services.s3.S3Methods;
import com.lucasrochagit.entities.business.BucketBusiness;
import com.lucasrochagit.entities.model.BucketModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author lucas
 */
public class DeleteBucket extends javax.swing.JFrame {

    private ArrayList<BucketModel> buckets;

    /**
     * Creates new form BucketDelete
     *
     * @param buckets
     */
    public DeleteBucket(ArrayList<BucketModel> buckets) {
        initComponents();
        appearance();

        this.buckets = buckets;

        deleteTitle.setEnabled(false);
        bucketName.setEnabled(false);
        delete.setEnabled(false);

        List<String> bucketsNames = new ArrayList<>();

        for (BucketModel b : buckets) {;
            bucketsNames.add(b.getName());
        }

        bucketOpt.setModel(
                new DefaultComboBoxModel
                    (bucketsNames.toArray(new String[bucketsNames.size()]))
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        emptyTitle = new javax.swing.JLabel();
        bucketOpt = new javax.swing.JComboBox<>();
        empty = new javax.swing.JLabel();
        deleteTitle = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        bucketName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("DELETE A BUCKET");
        title.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        emptyTitle.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        emptyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emptyTitle.setText("FIRST, EMPTY THE BUCKET:");

        bucketOpt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bucketOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        empty.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        empty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empty.setText("EMPTY");
        empty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emptyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emptyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emptyMouseExited(evt);
            }
        });

        deleteTitle.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        deleteTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteTitle.setText("NOW, DELETE A BUCKET");

        cancel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("CANCEL");
        cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });

        delete.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setText("DELETE");
        delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });

        bucketName.setEditable(false);
        bucketName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bucketName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bucketName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(deleteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(emptyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bucketName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bucketOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empty, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(emptyTitle)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bucketOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(deleteTitle)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bucketName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emptyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyMouseClicked
        // TODO add your handling code here:
        String[] options = {"Yes", "No"};
        int choice = JOptionPane
                .showOptionDialog(null,
                        "Are you sure?",
                        "Empty",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null,
                        options, options[0]);
        if (choice == 0) {
            if (S3Methods
                    .getInstance()
                    .emptyBucket(bucketOpt.getSelectedItem().toString())) {
                
                buckets = BucketBusiness
                        .getInstance()
                        .emptyBucket
                            (buckets, bucketOpt.getSelectedItem().toString());
                deleteTitle.setEnabled(true);
                bucketName.setEnabled(true);
                delete.setEnabled(true);
                emptyTitle.setEnabled(false);
                bucketOpt.setEnabled(false);
                empty.setEnabled(false);
                bucketName.setText(bucketOpt.getSelectedItem().toString());

            } else {
                JOptionPane
                        .showMessageDialog(null,
                            "The bucket could not be emptied. Try again later.",
                            "Information",
                            JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_emptyMouseClicked

    private void emptyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyMouseEntered
        // TODO add your handling code here:
        empty.setForeground(Color.BLUE);
    }//GEN-LAST:event_emptyMouseEntered

    private void emptyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyMouseExited
        // TODO add your handling code here:
        empty.setForeground(Color.BLACK);
    }//GEN-LAST:event_emptyMouseExited

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        // TODO add your handling code here:
        cancel.setForeground(Color.BLACK);
    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        // TODO add your handling code here:
        cancel.setForeground(Color.BLUE);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        MyBuckets b = new MyBuckets(buckets);
        this.dispose();
        b.setVisible(true);
    }//GEN-LAST:event_cancelMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        String[] options = {"Yes", "No"};
        int choice = JOptionPane
                .showOptionDialog(null,
                        "Are you sure?",
                        "Delete",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null,
                        options,
                        options[0]);
        if (choice == 0) {
            if (S3Methods
                    .getInstance()
                    .deleteEmptyBucket(bucketName.getText())) {
                buckets = BucketBusiness
                        .getInstance()
                        .deleteBucket(buckets, bucketName.getText());
                JOptionPane.showMessageDialog(null,
                        "Bucket deleted sucessfully!",
                        "Information",
                        JOptionPane.INFORMATION_MESSAGE);
                MyBuckets b = new MyBuckets(buckets);
                this.dispose();
                b.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null,
                        "The bucket could not be deleted. Try again later.",
                        "Information",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
        delete.setForeground(Color.BLUE);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
        delete.setForeground(Color.BLACK);
    }//GEN-LAST:event_deleteMouseExited

    public static void appearance() {
        try {
            UIManager
                .setLookAndFeel
                    ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException |
                InstantiationException |
                IllegalAccessException |
                javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger
                .getLogger
                    (Start.class.getName())
                        .log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bucketName;
    private javax.swing.JComboBox<String> bucketOpt;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel deleteTitle;
    private javax.swing.JLabel empty;
    private javax.swing.JLabel emptyTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
