/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lucasrochagit.views;


import com.lucasrochagit.entities.model.BucketModel;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author lucas
 */
public class Features extends javax.swing.JFrame {

    private final ArrayList<BucketModel> buckets;
    /**
     * Creates new form Features
     * @param buckets
     */
    
    public Features(ArrayList<BucketModel> buckets) {
        initComponents();
        appearance();
        this.buckets = buckets;
        ImageIcon icon = 
            new ImageIcon
                ("src/main/resources/com/lucasrochagit/interfaces/images/bucket.png");
        bucket.setIcon(icon);
        ImageIcon icon2 = 
            new ImageIcon
                ("src/main/resources/com/lucasrochagit/interfaces/images/files.png");
        file.setIcon(icon2);
        ImageIcon icon3 = 
            new ImageIcon
                ("src/main/resources/com/lucasrochagit/interfaces/images/upload.png");
        upload.setIcon(icon3);
        ImageIcon icon4 =
            new ImageIcon
                ("src/main/resources/com/lucasrochagit/interfaces/images/exit.png");
        exiting.setIcon(icon4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        file = new javax.swing.JLabel();
        myfiles = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        mybuckets = new javax.swing.JLabel();
        bucket = new javax.swing.JLabel();
        upload = new javax.swing.JLabel();
        uploaded = new javax.swing.JLabel();
        exiting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        file.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        file.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        myfiles.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        myfiles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myfiles.setText("MY FILES");
        myfiles.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        myfiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myfilesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myfilesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myfilesMouseExited(evt);
            }
        });

        exit.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("EXIT");
        exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        title.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("START MENU");
        title.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mybuckets.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        mybuckets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mybuckets.setText("MY BUCKETS");
        mybuckets.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mybuckets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mybuckets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mybucketsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mybucketsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mybucketsMouseExited(evt);
            }
        });

        bucket.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        bucket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        upload.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        upload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        uploaded.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        uploaded.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uploaded.setText("UPLOAD FILE");
        uploaded.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        uploaded.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploaded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uploadedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uploadedMouseExited(evt);
            }
        });

        exiting.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        exiting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(file, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(myfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bucket, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upload, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mybuckets, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploaded, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(exiting, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bucket, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mybuckets, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(upload, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploaded, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(file, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exiting, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        String[] options = {"Yes", "No"};
        int choice = JOptionPane
                .showOptionDialog(null, 
                        "Are you sure?",
                        "Exit",
                        JOptionPane.DEFAULT_OPTION, 
                        JOptionPane.INFORMATION_MESSAGE,
                        null, 
                        options, 
                        options[0]);
        if (choice == 0) {
            Start s = new Start();
            s.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void mybucketsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mybucketsMouseEntered
        // TODO add your handling code here:
        mybuckets.setForeground(Color.BLUE);
    }//GEN-LAST:event_mybucketsMouseEntered

    private void mybucketsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mybucketsMouseExited
        // TODO add your handling code here:
        mybuckets.setForeground(Color.BLACK);
    }//GEN-LAST:event_mybucketsMouseExited

    private void myfilesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myfilesMouseEntered
        // TODO add your handling code here:
        myfiles.setForeground(Color.BLUE);
    }//GEN-LAST:event_myfilesMouseEntered

    private void myfilesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myfilesMouseExited
        // TODO add your handling code here:
        myfiles.setForeground(Color.BLACK);
    }//GEN-LAST:event_myfilesMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        exit.setForeground(Color.BLUE);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitMouseExited

    private void mybucketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mybucketsMouseClicked
        // TODO add your handling code here:
        MyBuckets b = new MyBuckets(buckets);
        this.dispose();
        b.setVisible(true);
    }//GEN-LAST:event_mybucketsMouseClicked

    private void myfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myfilesMouseClicked
        // TODO add your handling code here:
        MyFiles f = new MyFiles(buckets);
        this.dispose();
        f.setVisible(true);
    }//GEN-LAST:event_myfilesMouseClicked

    private void uploadedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadedMouseClicked
        // TODO add your handling code here:
        UploadFile uf = new UploadFile(buckets);
        this.dispose();
        uf.setVisible(true);
    }//GEN-LAST:event_uploadedMouseClicked

    private void uploadedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadedMouseEntered
        // TODO add your handling code here:
        uploaded.setForeground(Color.BLUE);
    }//GEN-LAST:event_uploadedMouseEntered

    private void uploadedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadedMouseExited
        // TODO add your handling code here:
        uploaded.setForeground(Color.BLACK);

    }//GEN-LAST:event_uploadedMouseExited

    public static void appearance() {
        try {
            UIManager
                .setLookAndFeel
                    ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException |
                InstantiationException |
                IllegalAccessException |
                javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger
                    .getLogger
                        (Features.class.getName())
                            .log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bucket;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exiting;
    private javax.swing.JLabel file;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mybuckets;
    private javax.swing.JLabel myfiles;
    private javax.swing.JLabel title;
    private javax.swing.JLabel upload;
    private javax.swing.JLabel uploaded;
    // End of variables declaration//GEN-END:variables
}
