/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lucasrochagit.views;

import com.lucasrochagit.entities.model.BucketModel;
import com.lucasrochagit.utils.FileSize;
import com.lucasrochagit.views.tools.CellRender;
import com.lucasrochagit.views.tools.HeaderRenderer;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author lucas
 */
public class MyBuckets extends javax.swing.JFrame {

    private final ArrayList<BucketModel> buckets;

    /**
     * Creates new form Buckets
     *
     * @param buckets
     */
    public MyBuckets(ArrayList<BucketModel> buckets) {
        initComponents();
        appearance();

        this.buckets = buckets;

        JTableHeader cabecalho = bucketTable.getTableHeader();
        cabecalho.setDefaultRenderer(new HeaderRenderer(bucketTable));

        DefaultTableModel modelo = (DefaultTableModel) bucketTable.getModel();

        int cont = 1;
        for (BucketModel b : buckets) {
            modelo
                    .addRow(new Object[]{
                cont,
                b.getName(),
                b.getFiles().size(),
                FileSize.getInstance().formatFileSize(b.getSize())
            });
            cont++;
        }

        if (bucketTable.getRowCount() > 0) {
            bucketTable.setDefaultRenderer(Object.class, new CellRender());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bucketTable = new javax.swing.JTable();
        emptyBucket = new javax.swing.JLabel();
        deleteBucket = new javax.swing.JLabel();
        newBucket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        back.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK TO MENU");
        back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        title.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("MY BUCKETS");
        title.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        bucketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Name", "Number of Elements", "Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bucketTable);

        emptyBucket.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        emptyBucket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emptyBucket.setText("EMPTY BUCKET");
        emptyBucket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        emptyBucket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emptyBucket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emptyBucketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emptyBucketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emptyBucketMouseExited(evt);
            }
        });

        deleteBucket.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        deleteBucket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteBucket.setText("DELETE A BUCKET");
        deleteBucket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        deleteBucket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBucket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBucketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBucketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBucketMouseExited(evt);
            }
        });

        newBucket.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        newBucket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newBucket.setText("NEW BUCKET");
        newBucket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        newBucket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newBucket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBucketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newBucketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newBucketMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(emptyBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(deleteBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(186, 186, 186))))
                .addGap(90, 90, 90))
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emptyBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBucket, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        Features f = new Features(buckets);
        this.dispose();
        f.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setForeground(Color.BLUE);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setForeground(Color.BLACK);

    }//GEN-LAST:event_backMouseExited

    private void emptyBucketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyBucketMouseClicked
        // TODO add your handling code here:
        EmptyBucket eb = new EmptyBucket(buckets);
        this.dispose();
        eb.setVisible(true);
    }//GEN-LAST:event_emptyBucketMouseClicked

    private void emptyBucketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyBucketMouseEntered
        // TODO add your handling code here:
        emptyBucket.setForeground(Color.BLUE);
    }//GEN-LAST:event_emptyBucketMouseEntered

    private void emptyBucketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyBucketMouseExited
        // TODO add your handling code here:
        emptyBucket.setForeground(Color.BLACK);
    }//GEN-LAST:event_emptyBucketMouseExited

    private void deleteBucketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBucketMouseClicked
        // TODO add your handling code here:
        DeleteBucket db = new DeleteBucket(buckets);
        this.dispose();
        db.setVisible(true);
    }//GEN-LAST:event_deleteBucketMouseClicked

    private void deleteBucketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBucketMouseEntered
        // TODO add your handling code here:
        deleteBucket.setForeground(Color.BLUE);
    }//GEN-LAST:event_deleteBucketMouseEntered

    private void deleteBucketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBucketMouseExited
        // TODO add your handling code here:
        deleteBucket.setForeground(Color.BLACK);
    }//GEN-LAST:event_deleteBucketMouseExited

    private void newBucketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBucketMouseClicked
        // TODO add your handling code here:
        NewBucket nb = new NewBucket(buckets);
        this.dispose();
        nb.setVisible(true);
    }//GEN-LAST:event_newBucketMouseClicked

    private void newBucketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBucketMouseEntered
        // TODO add your handling code here:
        newBucket.setForeground(Color.BLUE);
    }//GEN-LAST:event_newBucketMouseEntered

    private void newBucketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBucketMouseExited
        // TODO add your handling code here:
        newBucket.setForeground(Color.BLACK);

    }//GEN-LAST:event_newBucketMouseExited

    public static void appearance() {
        try {
            UIManager
                    .setLookAndFeel
                        ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException
                | InstantiationException
                | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger
                    .getLogger(MyBuckets.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTable bucketTable;
    private javax.swing.JLabel deleteBucket;
    private javax.swing.JLabel emptyBucket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newBucket;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
